# -*- coding: utf-8 -*-
"""syntax-surgeon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gSxw1QLkNQC41QFPVQIO5FXDl4ZnsI3o
"""

!pip install -q gradio transformers torch black autopep8 reportlab requests

import torch
import ast
import re
import os
import io
import textwrap
import tempfile
import requests
from datetime import datetime

print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
else:
    print("Running on CPU — inference will be slower.")

class ChatbotConfig:
    MODEL_NAME = "ibm-granite/granite-3.3-2b-instruct"
    DEFAULT_TEMP = 0.7
    DEFAULT_MAX_TOKENS = 256
    DEFAULT_TOP_P = 0.95
    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

print(f"Model  : {ChatbotConfig.MODEL_NAME}")
print(f"Device : {ChatbotConfig.DEVICE}")

from transformers import pipeline

print("Loading IBM Granite model (this may take a few minutes)...")

model_pipe = pipeline(
    "text-generation",
    model=ChatbotConfig.MODEL_NAME,
    device=0 if ChatbotConfig.DEVICE == "cuda" else -1,
    torch_dtype=torch.float16 if ChatbotConfig.DEVICE == "cuda" else torch.float32,
)

print(" Model loaded successfully!")

def detect_python_code(text):
    patterns = [
        r'def\s+\w+\s*\(',
        r'class\s+\w+',
        r'import\s+\w+',
        r'from\s+\w+\s+import',
        r'if\s+.*:',
        r'for\s+.*\s+in\s+',
        r'while\s+.*:',
        r'```python',
        r'print\s*\(',
        r'return\s+',
    ]
    return any(re.search(p, text) for p in patterns)


# -- 2.2 Syntax Validation --
def check_syntax(code):
    try:
        ast.parse(code)
        return True, None
    except SyntaxError as e:
        return False, f"Syntax Error (line {e.lineno}): {e.msg}"
    except Exception as e:
        return False, str(e)


# -- 2.3 Code Fixing Engine --
def fix_code_indentation(code):
    lines = code.splitlines()
    return '\n'.join(line.rstrip().replace('\t', '    ') for line in lines)


def fix_code_brackets(code):
    pairs = {'(': ')', '[': ']', '{': '}'}
    stack = []
    for ch in code:
        if ch in pairs:
            stack.append(pairs[ch])
        elif ch in pairs.values():
            if stack and stack[-1] == ch:
                stack.pop()
    return code + ''.join(reversed(stack))


def format_code(code):
    try:
        import black
        return black.format_str(code, mode=black.Mode())
    except Exception:
        pass
    try:
        import autopep8
        return autopep8.fix_code(code, options={'aggressive': 1})
    except Exception:
        return code


def fix_python_code(code):
    code = re.sub(r'^```python\s*', '', code.strip(), flags=re.MULTILINE)
    code = re.sub(r'```$', '', code.strip(), flags=re.MULTILINE)
    code = code.strip()
    original, changes = code, []

    fixed = fix_code_indentation(code)
    if fixed != code:
        changes.append("Normalised indentation (tabs to spaces)")
    code = fixed

    fixed = fix_code_brackets(code)
    if fixed != code:
        changes.append("Balanced unmatched brackets/parentheses")
    code = fixed

    formatted = format_code(code)
    if formatted.strip() != code.strip():
        changes.append("Applied PEP 8 formatting (Black/autopep8)")
    code = formatted

    is_valid, error = check_syntax(code)
    return {'original': original, 'fixed': code,
            'syntax_valid': is_valid, 'error': error, 'changes': changes}


# -- 3.1 Conversation History --
conversation_history = []

def reset_history():
    global conversation_history
    conversation_history = []


# -- 3.2 Response Generation --
def generate_response(user_message, temperature, max_tokens, top_p):
    global conversation_history
    conversation_history.append({"role": "user", "content": user_message})
    try:
        output = model_pipe(
            conversation_history,
            max_new_tokens=int(max_tokens),
            temperature=temperature,
            do_sample=True,
            top_p=top_p,
        )
        reply = output[0]["generated_text"][-1]["content"]
    except Exception as e:
        reply = f"Model error: {e}"
    conversation_history.append({"role": "assistant", "content": reply})
    return reply


# -- 4.2 Export Utilities --
def download_txt():
    if not conversation_history:
        return None, "No conversation to export."
    lines = ["=== The Syntax Surgeon - Chat Export ===",
             f"Exported : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
             f"Messages : {len(conversation_history)}",
             "=" * 50, ""]
    for msg in conversation_history:
        lines += [f"[{msg['role'].upper()}]", msg['content'], ""]
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".txt",
                                      mode="w", encoding="utf-8")
    tmp.write('\n'.join(lines))
    tmp.close()
    return tmp.name, "TXT export ready."


def download_pdf():
    if not conversation_history:
        return None, "No conversation to export."
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib import colors
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch

        tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
        doc = SimpleDocTemplate(tmp.name, pagesize=letter,
                                leftMargin=inch, rightMargin=inch,
                                topMargin=inch, bottomMargin=inch)
        styles = getSampleStyleSheet()
        user_style = ParagraphStyle('User', parent=styles['Normal'],
                                    textColor=colors.HexColor('#1a3c6e'),
                                    fontName='Helvetica-Bold', fontSize=10)
        asst_style = ParagraphStyle('Asst', parent=styles['Normal'],
                                    textColor=colors.HexColor('#4b0082'),
                                    fontName='Helvetica', fontSize=10)
        story = [
            Paragraph("The Syntax Surgeon - Chat Export", styles['Title']),
            Paragraph(
                f"Exported: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | "
                f"Messages: {len(conversation_history)}", styles['Normal']),
            Spacer(1, 0.2 * inch),
        ]
        for msg in conversation_history:
            role = msg['role'].upper()
            content = msg['content'].replace('<', '&lt;').replace('>', '&gt;')
            style = user_style if msg['role'] == 'user' else asst_style
            story.append(Paragraph(f"<b>[{role}]</b>", style))
            for line in content.split('\n'):
                story.append(Paragraph(line or "&nbsp;", styles['Normal']))
            story.append(Spacer(1, 0.15 * inch))
        doc.build(story)
        tmp.close()
        return tmp.name, "PDF export ready."
    except Exception as e:
        return None, f"PDF error: {e}"


# -- 4.3 Pastebin Share --
def generate_share_link():
    if not conversation_history:
        return "No conversation to share."
    lines = ["The Syntax Surgeon - Shared Chat",
             f"Shared: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
             "=" * 50]
    for msg in conversation_history:
        lines += [f"\n[{msg['role'].upper()}]", msg['content']]
    try:
        resp = requests.post(
            'https://pastebin.com/api/api_post.php',
            data={
                'api_dev_key':          'PASTE_YOUR_PASTEBIN_API_KEY_HERE',
                'api_option':           'paste',
                'api_paste_code':       '\n'.join(lines),
                'api_paste_name':       'Syntax Surgeon Chat',
                'api_paste_expire_date':'1W',
                'api_paste_private':    '0',
            }, timeout=10)
        if resp.status_code == 200 and resp.text.startswith('https'):
            return f"Share link: {resp.text.strip()}"
        return f"Pastebin response: {resp.text}"
    except Exception as e:
        return f"Share error: {e}"


print("All core functions defined successfully.")

def chat_handler(user_message, chat_history, temperature, max_tokens, top_p):
    if not user_message.strip():
        return chat_history, ""
    parts = []
    if detect_python_code(user_message):
        result = fix_python_code(user_message)
        if result['changes']:
            parts.append("**Code fixes applied:**")
            parts += [f"  - {c}" for c in result['changes']]
            parts.append("")
        parts.append("Syntax valid." if result['syntax_valid']
                     else f"Remaining issue: {result['error']}")
        parts.append("\n**Fixed code:**")
        parts.append(f"```python\n{result['fixed']}\n```")
        prompt = (f"Briefly explain what this fixed Python code does:\n\n"
                  f"```python\n{result['fixed']}\n```")
        parts.append("\n**Explanation:**")
        parts.append(generate_response(prompt, temperature, max_tokens, top_p))
    else:
        parts.append(generate_response(user_message, temperature,
                                       int(max_tokens), top_p))
    chat_history.append((user_message, '\n'.join(parts)))
    return chat_history, ""


def clear_chat():
    reset_history()
    return [], "Chat cleared."


print("Chat handler ready.")

import gradio as gr

with gr.Blocks(title="The Syntax Surgeon", theme=gr.themes.Soft()) as demo:

    gr.Markdown("# The Syntax Surgeon\n**AI-Powered Code Fixer** powered by IBM Granite 3.3 2B")

    with gr.Row():
        with gr.Column(scale=3):
            chatbot   = gr.Chatbot(height=420, label="Conversation",
                                   bubble_full_width=False)
            msg_input = gr.Textbox(lines=3, label="Your message",
                                   placeholder="Ask anything or paste Python code to fix...")
            send_btn  = gr.Button("Send", variant="primary")
            with gr.Accordion("Model Parameters", open=False):
                temperature = gr.Slider(0.1, 1.0,
                                        value=ChatbotConfig.DEFAULT_TEMP,
                                        step=0.05, label="Temperature")
                max_tokens  = gr.Slider(50, 1024,
                                        value=ChatbotConfig.DEFAULT_MAX_TOKENS,
                                        step=50, label="Max Tokens")
                top_p       = gr.Slider(0.1, 1.0,
                                        value=ChatbotConfig.DEFAULT_TOP_P,
                                        step=0.05, label="Top-P")

        with gr.Column(scale=1):
            clear_btn  = gr.Button("Clear Chat")
            dl_txt_btn = gr.Button("Download TXT")
            dl_pdf_btn = gr.Button("Download PDF")
            share_btn  = gr.Button("Share (Pastebin)")
            status_box = gr.Textbox(label="Status", interactive=False, lines=2)
            txt_file   = gr.File(label="TXT", visible=False)
            pdf_file   = gr.File(label="PDF", visible=False)

    send_btn.click(chat_handler,
                   [msg_input, chatbot, temperature, max_tokens, top_p],
                   [chatbot, msg_input])
    msg_input.submit(chat_handler,
                     [msg_input, chatbot, temperature, max_tokens, top_p],
                     [chatbot, msg_input])
    clear_btn.click(clear_chat, outputs=[chatbot, status_box])

    def handle_txt():
        path, msg = download_txt()
        return (gr.File(value=path, visible=True) if path
                else gr.File(visible=False)), msg

    def handle_pdf():
        path, msg = download_pdf()
        return (gr.File(value=path, visible=True) if path
                else gr.File(visible=False)), msg

    dl_txt_btn.click(handle_txt, outputs=[txt_file, status_box])
    dl_pdf_btn.click(handle_pdf, outputs=[pdf_file, status_box])
    share_btn.click(generate_share_link, outputs=status_box)

demo.launch(share=True)